micronaut:
  application:
    name: authentication
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

---
micronaut:
  security:
    token:
      jwt:
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
---
kafka:
  producers:
    logged-username-client:
      retries: 3
  bootstrap:
    servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
---
mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
  database: authentication
  collection:
    account: account
    refreshToken: refreshToken
